### ISSUE TITLE
Android App crashes on launch due to Firebase

### ISSUE THREAD

**Issue by thepoppingone** [emartech/react-native-emarsys-sdk#42]
App crashes when importing two Firebase implementations:
### Scenario 1 
Just updating the SDK to 3.0 of Emarsys the notifications does not get sent
```
    // Push notifications
    implementation project(':react-native-notifications');
    implementation 'com.google.firebase:firebase-core:19.0.0';

    // Emarsys
    implementation "com.emarsys:emarsys-sdk:3.0.0"

```

### Scenario 2
If we add Firebase emarsys lib as well, our app keeps crashing due to the error below BUT we are able to receive push notifs from Emarsys

```
    // Push notifications
    implementation project(':react-native-notifications');

    // Emarsys
    implementation "com.emarsys:emarsys-sdk:3.0.0"
    implementation 'com.emarsys:emarsys-firebase:+'

```

### Scenario 3
When we add all these 4 libraries, it works on Android 10 but not Android 11

```
    // Push notifications
    implementation project(':react-native-notifications');
    implementation 'com.google.firebase:firebase-core:19.0.0';

    // Emarsys
    implementation "com.emarsys:emarsys-sdk:3.0.0"
    implementation 'com.emarsys:emarsys-firebase:+'

```

It seems that the Firebase-core lib is clashing with the Emarsys Firebase lib, can you guys clarify what Firebase lib we can use to prevent our app from crashing?

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/~~1ReTA_TmpZYGW2k-SLIcYA==/com.company.dev2-GDIbOnok073A7t0MV59IdQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~1ReTA_TmpZYGW2k-SLIcYA==/com.company.dev2-GDIbOnok073A7t0MV59IdQ==/lib/arm64, /data/app/~~1ReTA_TmpZYGW2k-SLIcYA==/com.company.dev2-GDIbOnok073A7t0MV59IdQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/
```

Tested on both Android 10 and Android 11 Devices with GoogleMobileServices

**Comment by thepoppingone** [comment]
More logs for debug:
```
 ChimeNotiEventHandler: Successfully recorded chime actions: DISPLAYED_NOTIFICATION
08-16 17:14:34.067 12260 12568 E A       : Processing of GCM event failed.
08-16 17:14:34.067 12260 12568 E A       : java.lang.NullPointerException: No binary data in push message
08-16 17:14:34.067 12260 12568 E A       : 	at com.google.common.base.bb.a(SourceFile:1)
08-16 17:14:34.067 12260 12568 E A       : 	at com.google.android.apps.gsa.staticplugins.be.k.b(SourceFile:6)
08-16 17:14:34.067 12260 12568 E A       : 	at dagger.b.a.h.a(SourceFile:2)
08-16 17:14:34.067 12260 12568 E A       : 	at com.google.common.w.a.f.d(SourceFile:2)
08-16 17:14:34.067 12260 12568 E A       : 	at com.google.common.w.a.h.run(SourceFile:9)
08-16 17:14:34.067 12260 12568 E A       : 	at com.google.ce.h.a.q.run(SourceFile:3)
08-16 17:14:34.067 12260 12568 E A       : 	at com.google.android.libraries.g.ab.run(SourceFile:1)
08-16 17:14:34.067 12260 12568 E A       : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-16 17:14:34.067 12260 12568 E A       : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-16 17:14:34.067 12260 12568 E A       : 	at com.google.android.libraries.g.n.run(SourceFile:2)
08-16 17:14:34.067 12260 12568 E A       : 	at com.google.android.libraries.g.d.run(SourceFile:2)
08-16 17:14:34.067 12260 12568 E A       : 	at java.lang.Thread.run(Thread.java:923)
08-16 17:14:34.070  3513  3513 W GCM     : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.google.android.googlequicksearchbox (has extras) }
08-16 17:14:34.149  3513 23653 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskService started execution. cause:7 exec_start_elapsed_seconds: 252558 [CONTEXT service_id=218 ]
08-16 17:14:34.169  3513 23653 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskService finished executing. cause:7 result: 1 elapsed_millis: 45 uptime_millis: 45 exec_start_elapsed_seconds: 252558 [CONTEXT service_id=218 ]
08-16 17:14:30.755  1687  2783 I chatty  : uid=1000(system) ConnectivitySer identical 10 lines
```

```
08-16 17:21:48.319 24712 24784 D RNEmarsysEventHandler: Registered for events.

**Comment by eduzatoni** [comment]
Hi @thepoppingone,

Could you please provide your full app build.grade and AndroidManifest.xml?

We are not able to reproduce this crash. You can have a look at our [sample app](https://github.com/emartech/react-native-emarsys-sdk/tree/master/sample) to see if you can spot anything different from your app.

**Comment by thepoppingone** [comment]
Thanks for the response, it seems to not crash on launch now after modifying the Manifest and build.gradle upon referencing the sample 

However, it crashes when this async task is performed 
```
08-16 23:53:47.868 24553 24610 I ReactNativeNotifs: App initialized => asking for new token
08-16 23:53:47.872 24553 24610 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
08-16 23:53:47.872 24553 24610 E AndroidRuntime: Process: com.stashaway.dev2, PID: 24553
08-16 23:53:47.872 24553 24610 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at com.wix.reactnativenotifications.fcm.FcmToken.refreshToken(FcmToken.java:78)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at com.wix.reactnativenotifications.fcm.FcmToken.onAppReady(FcmToken.java:68)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at com.wix.reactnativenotifications.fcm.FcmInstanceIdRefreshHandlerService.onHandleWork(FcmInstanceIdRefreshHandlerService.java:26)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	... 3 more
08-16 23:53:47.872 24553 24610 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/~~KgVTsdOW38TWDiPqrngjag==/com.aaa.dev2-gsvjfnks1kI1TmWcbdOOGA==/base.apk"],nativeLibraryDirectories=[/data/app/~~KgVTsdOW38TWDiPqrngjag==/com.aaa.dev2-gsvjfnks1kI1TmWcbdOOGA==/lib/arm64, /data/app/~~KgVTsdOW38TWDiPqrngjag==/com.aaa.dev2-gsvjfnks1kI1TmWcbdOOGA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-16 23:53:47.872 24553 24610 E AndroidRuntime: 	... 10 more
```

Before the upgrade of SDK this was not happening. 

### Android Manifest:
```
<!-- firebase (text/face recognition) -->
      <meta-data
          android:name="com.google.firebase.ml.vision.DEPENDENCIES"
          android:value="ocr, face" />

      <service android:name="com.emarsys.service.EmarsysFirebaseMessagingService">
        <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT"/>
        </intent-filter>
      </service>


```

### Build.gradle
```
dependencies {
    // Test remove this line
    //implementation project(':react-native-emarsys-wrapper')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    // Flipper dependencies (debug only)
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.flipper'
    }
    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }

    // IDFA
    implementation 'com.google.android.gms:play-services-ads:15.0.0'

    // Push notifications
    implementation project(':react-native-notifications');
    implementation 'com.google.firebase:firebase-core:19.0.0';  

    // Emarsys
    implementation "com.emarsys:emarsys-sdk:3.0.0"
    implementation 'com.emarsys:emarsys-firebase:+'

    // Detox
    androidTestImplementation('com.wix:detox:+') { transitive = true }
    androidTestImplementation 'junit:junit:4.12'

    // part of 0.62.2 RN upgrade
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    // https://reactnative.dev/docs/0.62/image#gif-and-webp-support-on-android
    implementation 'com.facebook.fresco:animated-gif:2.0.0'

    implementation project(':@sentry_react-native')
}
```

**Comment by thepoppingone** [comment]
We probably need to know what version of Firebase that is being used on `com.emarsys:emarsys-firebase:+` to understand which matching 
```
    // IDFA
    implementation 'com.google.android.gms:play-services-ads:15.0.0'

    // Push notifications
    implementation project(':react-native-notifications');
    implementation 'com.google.firebase:firebase-core:19.0.0';
    ```
    
    to use to prevent clashing, please provide more info to us if possible too!

**Comment by thepoppingone** [comment]
Ok i managed to resolve it by upgrading the Node library `react-native-notifications` to the latest version of `4.1.2`

Now it is working fine with notifications able to be received on Android 11 devices, will update after Android 10 devices are tested.

**Comment by eduzatoni** [comment]
Hey @thepoppingone,

Good to know that! 🥳 

Have you tested it on Android 10? Can this issue be closed?

Best,
Edu

**Comment by thepoppingone** [comment]
The latest tests we had it still crashes on Android 10, will keep this issue updated if we have more info
