### ISSUE TITLE
Android App crashing at EmarsysConfig.Builder() 

### ISSUE THREAD

**Issue by johnhaup** [emartech/react-native-emarsys-sdk#47]
Hello,

We had the Android app up and receiving push notifications a few days ago, and today it is crashing with this error:
```
2021-09-30 14:56:53.053 23849-23892/com.bento.fabletics E/AndroidRuntime: FATAL EXCEPTION: CoreSDKHandlerThread-c0cde547-d995-48a1-a500-30315e37da74
    Process: com.<edited out app name>, PID: 23849
    java.lang.NoSuchMethodError: No direct method <init>(Lcom/emarsys/mobileengage/client/ClientServiceInternal;Lcom/emarsys/core/storage/Storage;Lcom/emarsys/core/device/DeviceInfo;)V in class Lcom/emarsys/mobileengage/device/DeviceInfoStartAction; or its super classes (declaration of 'com.emarsys.mobileengage.device.DeviceInfoStartAction' appears in /data/app/~~X3DfAF2RAQYIcyEnggt0nw==/com.bento.fabletics-FicwuwfEO7O38hvtY3ydDg==/base.apk)
        at com.emarsys.di.DefaultEmarsysComponent$activityLifecycleWatchdog$2.invoke(DefaultEmarsysComponent.kt:243)
        at com.emarsys.di.DefaultEmarsysComponent$activityLifecycleWatchdog$2.invoke(DefaultEmarsysComponent.kt:241)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.emarsys.di.DefaultEmarsysComponent.getActivityLifecycleWatchdog(DefaultEmarsysComponent.kt:241)
        at com.emarsys.Emarsys.registerWatchDogs(Emarsys.kt:188)
        at com.emarsys.Emarsys.setup$lambda-1(Emarsys.kt:89)
        at com.emarsys.Emarsys.lambda$ptEL2JaL5vZsDbZ00oOoLdLsAVQ(Unknown Source:0)
        at com.emarsys.-$$Lambda$Emarsys$ptEL2JaL5vZsDbZ00oOoLdLsAVQ.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.emarsys.core.concurrency.CoreHandler.dispatchMessage(CoreHandler.kt:13)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

We have these in our app/build.gradle dependencies:
```
    implementation "com.emarsys:emarsys-sdk:3.0.0"
    implementation "com.emarsys:emarsys-firebase:+"
```
I've tried sdk 3.0.0, 3.0.1, and 3.1.0 and get the above error.

This is from the android dependency tree from the app:
```
+--- com.emarsys:emarsys-sdk:3.0.0@aar
+--- com.emarsys:emarsys:3.0.0@aar
+--- com.emarsys:mobile-engage:3.1.1@aar
+--- com.emarsys:mobile-engage-api:3.1.1@aar
+--- com.emarsys:predict:3.0.0@aar
+--- com.emarsys:predict-api:3.0.0@aar
+--- com.emarsys:common:3.1.1@aar
+--- com.emarsys:core:3.1.1@aar
+--- com.emarsys:core-api:3.1.1@aar
```

Could it be something to do with some sub-dependencies being on 3.1.1 instead of 3.0.0?  The error above references core and mobile-engage, which both look to be on 3.1.1.  I also noticed 3.1.1 in the Android repo was pushed but seems to be failing it's builds.

Also of note, if I remove the Emarsys logic from our onCreate method in MainApplication.java, the app builds.  The EmarysysConfig.Builder seems to be where the error is getting thrown.
```
    @Override
    public void onCreate() {
        super.onCreate();

        SoLoader.init(this, /* native exopackage */ false);

        EmarsysConfig config = new EmarsysConfig.Builder()
            .application(this)
            .applicationCode(<edited>)
            .merchantId(<edited>)
            .build();
        Emarsys.setup(config);
        createNotificationChannels();

        RNBranchModule.getAutoInstance(this);
        BugsnagReactNative.start(this);
    }
```

I appreciate any help you can offer!

Thank you.

**Comment by johnhaup** [comment]
It looks like it is an issue with the dependency versions not matching.  Locking the versions in my build.gradle to match the version this wrapper library uses fixed my issue:
```
    implementation "com.emarsys:emarsys-sdk:3.0.0"
    implementation("com.emarsys:mobile-engage:3.0.0") {
        version {
            strictly "3.0.0"
        }
    }
    implementation("com.emarsys:mobile-engage-api:3.0.0") {
        version {
            strictly "3.0.0"
        }
    }
    implementation("com.emarsys:core:3.0.0") {
        version {
            strictly "3.0.0"
        }
    }
    implementation("com.emarsys:core-api:3.0.0") {
        version {
            strictly "3.0.0"
        }
    }
    implementation "com.emarsys:emarsys-firebase:+"
```

Now my dependency tree shows:
```
+--- com.emarsys:emarsys-sdk:3.0.0@aar
+--- com.emarsys:emarsys:3.0.0@aar
+--- com.emarsys:mobile-engage:3.0.0@aar
+--- com.emarsys:mobile-engage-api:3.0.0@aar
+--- com.emarsys:predict:3.0.0@aar
+--- com.emarsys:predict-api:3.0.0@aar
+--- com.emarsys:core:3.0.0@aar
+--- com.emarsys:common:3.0.0@aar
+--- com.emarsys:core-api:3.0.0@aar
```

**Comment by johnhaup** [comment]
@nmsdvid that's interesting, leaving the firebase version at `'com.emarsys:emarsys-firebase:+'` still allows the app to build for me, but I have to apply the above changes to the submodules.
